apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: Istio
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: default
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: Istio
    repoURL: 'https://github.com/priyaaakansha/Argo-Istio-demo'
    targetRevision: HEAD